/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

#include <stdio.h>

int main()
{
    int i, soma = 0, ini = 0, fim = 1, aux = 0;

        for(i = 1; i < 70; i++){
            if (soma % 2 == 0){
                if (soma < 4000000){
                    printf("soma de %d = %d    ", i-1, soma);
                    aux += soma;
                    printf("soma dos pares = %d\n", aux);
                }else{
                    break;
                }
            }
            soma = ini + fim;
            ini = fim;
            fim = soma;
        }

    printf("SOMA DOS PARES FINAL = %d\n", aux);
    getchar();
    return 0;
}
